image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

build_stage:
  stage: build
  only:
    - master
    - release
  script:
    - touch ./src/scss/fonts/fonts.scss
    - npm install
    - npm run build -- --prod --aot --output-path=./dist/out --configuration production
  artifacts:
    paths:
      - dist/out
  tags:
    - docker
