image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

build_stage:
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build -- --output-path=./dist/out --configuration production
  artifacts:
    expire_in: 1 day
    paths:
      - dist/out
  tags:
    - docker
