image: trion/ng-cli-karma

stages:
  - build

cache:
  paths:
    - node_modules/

build_other:
  stage: build
  only:
    - triggers
    - schedules
  script:
    - npm install
    - npm run build -- --output-path=./dist/out
  artifacts:
    expire_in: 5 days
    paths:
      - dist/out
  tags:
    - docker

build_master:
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build -- --output-path=./dist/out
  artifacts:
    expire_in: 90 days
    paths:
      - dist/out
  tags:
    - docker

build_release:
  stage: build
  only:
    - release
  script:
    - npm install
    - npm run build -- --prod --aot --output-path=./dist/out --configuration production
  artifacts:
    expire_in: 30 days
    paths:
      - dist/out
  tags:
    - docker
